# Metsähovi skycam config file example
# Olli Wilkman 2016

[main]
update_interval = 1 # seconds # TODO (not implemented)
show_skycam = true # TODO (not implemented)
show_aircraft = true # TODO (not implemented)
show_satellites = true # TODO (not implemented)

[skycam]
update_interval = 60 # seconds # TODO (not implemented)
image_path = "test"
image_name = "ImageLastFTP_AllSKY.png"
north_offset = 13.68 # degrees # TODO (not implemented)

[satellites]
color = "yellow" # TODO (not implemented)
show_name = true # TODO (not implemented)
trace_interval = 1 # minutes # TODO (not implemented)
trace_forward = 5 # TODO (not implemented)
trace_backward = 1 # TODO (not implemented)
trace_show_time = true # TODO (not implemented)
files = ["geodetic.txt", "science.txt"] # TODO (not implemented)

[aircraft]
address = "localhost" # TODO (not implemented)
port = 7879 # TODO (not implemented)
show_vectors = true # TODO (not implemented)
color = "purple" # TODO (not implemented)
warn_nearby = true # TODO (not implemented)


[telescope]
address = "localhost" # TODO (not implemented)
port = 7879 # TODO (not implemented)
color_normal = "blue" # TODO (not implemented)
color_warning = "red" # TODO (not implemented)


