# Metsähovi skycam config file example
# Olli Wilkman 2016

[main]
update_interval = 0.5 # seconds
show_skycam = true
show_aircraft = true
show_satellites = true
debug_level = 1

[skycam]
update_interval = 60 # seconds
image_path = "test"
image_name = "ImageLastFTP_AllSKY.png"
north_offset = 14.3 # degrees

[satellite]
color = "yellow"
show_name = true # TODO (not implemented)
trace_interval = 1 # minutes # TODO (not implemented)
trace_forward = 5 # TODO (not implemented)
trace_backward = 1 # TODO (not implemented)
trace_show_time = true # TODO (not implemented)
files = ["geodetic.txt", "iss.txt"]
names = []

[aircraft]
address = "localhost"
port = 7879
show_vectors = true
color = "purple"
color_warning = "red"
min_altitude = 15 # degrees
max_distance = 100
warn_zenith = true # TODO (not implemented)
warn_scope = true # TODO (not implemented)
warn_nearby = true
nearby_distance = 20

[telescope]
address = "localhost"
port = 7879
color_normal = "blue" # TODO (not implemented)
color_warning = "red" # TODO (not implemented)
