# Metsähovi skycam config file example
# Olli Wilkman 2016

[main]
update_interval = 0.5 # seconds
show_skycam = true
show_aircraft = true
show_satellites = true
show_scope = true # TODO (not implemented)
debug_level = 1

[skycam]
update_interval = 60 # seconds
image_path = "test"
image_name = "ImageLastFTP_AllSKY.jpg"
default_image = "image_blank.png"
north_offset = -61 # degrees
draw_horizon = 5 # degrees

[satellite]
color = "yellow"
show_names = true
show_traces = true
trace_interval = 20 # seconds
trace_forward = 6 # steps
trace_backward = 2 # steps
trace_show_time = true # TODO (not implemented)
files = ["geodetic.txt"]
names = []
min_altitude = 5.0 # degrees
max_range = 370000.0
show_eclipsed = true

[aircraft]
address = "localhost"
port = 7879
show_vectors = true
color = "purple"
color_warning = "red"
min_altitude = 15 # degrees
max_distance = 100 # km
warn_zenith = true # TODO (not implemented)
warn_scope = true # TODO (not implemented)
warn_nearby = false
nearby_distance = 20 # km

[telescope]
address = "localhost"
port = 7879
color_normal = "blue" # TODO (not implemented)
color_warning = "red" # TODO (not implemented)
