# Metsähovi skycam config file example
# Olli Wilkman 2016

[main]
update_interval = 0.5 # seconds
show_skycam = true
show_aircraft = true
show_satellites = true
show_scope = true # TODO (not implemented)
debug_level = 1

[skycam]
update_interval = 60 # seconds
image_path = "test"
image_name = "ImageLastFTP_AllSKY.png"
default_image = "image_blank.png"
north_offset = 13.9 # degrees

[satellite]
color = "yellow"
show_names = true
show_traces = true
trace_interval = 10 # seconds
trace_forward = 20
trace_backward = 2
trace_show_time = true # TODO (not implemented)
files = ["geodetic.txt", "iss.txt", "science.txt"]
names = []
min_altitude = 0.0 # degrees
max_range = 1000.0 # km # TODO (not implemented)
show_eclipsed = true # TODO (not implemented)

[aircraft]
address = "localhost"
port = 7879
show_vectors = true
color = "purple"
color_warning = "red"
min_altitude = 15 # degrees
max_distance = 100 # km
warn_zenith = true # TODO (not implemented)
warn_scope = true # TODO (not implemented)
warn_nearby = false
nearby_distance = 20 # km

[telescope]
address = "localhost"
port = 7879
color_normal = "blue" # TODO (not implemented)
color_warning = "red" # TODO (not implemented)
